### ISSUE TITLE
Serial monitor doesn't work with custom port

### ISSUE THREAD

**Issue by Markomas** [pavelmc/amake#10]
amake ignores custom port, it always uses /dev/ttyUSB0

Example:

`$ amake -s 115200 /dev/ttyACM0`

```
amake - version 1.2 by Pavel Milanes, pavelmc@gmail.com, CO7WT
A very simple Arduino IDE command line interface for Linux
Using the Arduno IDE from here:
/usr/bin/arduino
===============================================================

Opening Serial Comms [Ctrl+C to exit]
=====================================
/usr/local/bin/amake: line 801: /dev/ttyUSB0: No such file or directory

```

**Comment by pavelmc** [comment]
Thanks @Markomas  for the bug spot and patch.

I improved it a bit with some ideas in the TODO list; now the serial speed is extracted from the .ino files in the project folder and watch out! the syntax changed.

amake -s /dev/ttyUSB0 115200
amake -s /dev/ttyUSB0
amake -s

Now is possible to do "amake -s" and it will work 100% of the time if you run it inside the project folder (serial speed auto-detection) and your USB is auto-detected successfully.

Aka: if you can make a -v & then a -u successfuly the -s will work out of the box.
